name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For available runner types, refer to GitHub documentation

    env:
      Solution_Name: SimFlow.sln  # Replace with your solution name
      # Test_Project_Path: your-test-project-path
      # Wap_Project_Directory: your-wap-project-directory-name
      # Wap_Project_Path: your-wap-project-path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # (Optional) Run unit tests if needed
    # - name: Execute unit tests
    #   run: dotnet test

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # (Optional) Package the application if needed, but without signing
    # Example: If you have a WAP project (Windows Application Packaging)
    # - name: Create the app package
    #   run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:AppxBundle=Always /p:Appx_Bundle_Platforms=x86|x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: $env:Solution_Name\bin\$(BuildConfiguration)\$(TargetFramework)  # Modify this path as per your build output directory
